<word>dbg</word>
<word>msg</word>
<word>Debug</word>
<word>Warn</word>
<word>Error</word>
<word>Time2Str</word>
<word>GetAllDays</word>
<word>GetAllWeeks</word>
<word>GetAllMonths</word>
<word>GetAllYears</word>
<word>GetAllTime</word>
<word>GetYear</word>
<word>GetMonth</word>
<word>GetDay</word>
<word>GetWeek</word>
<word>SetInt</word>
<word>GetInt</word>
<word>SetStr</word>
<word>GetStr</word>
<word>NotifyVar</word>
<word>SysMsg_SendTopMsg</word>
<word>SysMsg_SendCenterMsg</word>
<word>SysMsg_SendBroadcastMsg</word>
<word>SysMsg_SendRoleTalk</word>
<word>SysMsg_SendGuildMsg</word>
<word>SysMsg_SendMapMsg</word>
<word>InputDlg</word>
<word>MsgBox</word>
<word>WebBox</word>
<word>SysMsg_SendBroadcastColor</word>
<word>SysMsg_SendBottomColor</word>
<word>SysMsg_SendTopColor</word>
<word>Name</word>
<word>KeyName</word>
<word>X</word>
<word>Y</word>
<word>Distance</word>
<word>MapGuid</word>
<word>AddBuff</word>
<word>AddBuff2</word>
<word>AddBuffEx</word>
<word>DelBuff</word>
<word>HasBuff</word>
<word>Kill</word>
<word>AddSkill</word>
<word>HasSkill</word>
<word>SetPanelSize</word>
<word>SendRoleHPNtf</word>
<word>Camp</word>
<word>SetCamp</word>
<word>Player_GetAccountID</word>
<word>Player_GetServantCount</word>
<word>Player_GetServantList</word>
<word>Player_IsServantNear</word>
<word>Player_GetAttackMode</word>
<word>ItemCountByKey</word>
<word>BagSize</word>
<word>BagFree</word>
<word>AccountName</word>
<word>Ip</word>
<word>Name2Guid</word>
<word>GuildGuid</word>
<word>ReliveMapGuid</word>
<word>Player_GetGuildCtrb</word>
<word>Player_ReCalGuildCtrb</word>
<word>Player_GetTeamGuid</word>
<word>Player_GetTeamList</word>
<word>Player_GetCastleList</word>
<word>BagItemList</word>
<word>Player_HasTeam</word>
<word>Player_IsTeamLeader</word>
<word>Player_IsGuildLeader</word>
<word>Player_IsViceGuildLeader</word>
<word>Player_IsGM</word>
<word>Player_ChangeAttackMode</word>
<word>Player_AddGold</word>
<word>Player_SubGold</word>
<word>Player_IsGoldEnough</word>
<word>Player_AddIngot</word>
<word>Player_SubIngot</word>
<word>Player_IsIngotEnough</word>
<word>Player_AddExp</word>
<word>Player_SubExp</word>
<word>Player_AddIntegral</word>
<word>Player_SubIntegral</word>
<word>Player_IsIntegralEnough</word>
<word>Player_Relive</word>
<word>Player_JumpToRole</word>
<word>Player_DragFromRole</word>
<word>Player_FixEquip</word>
<word>Player_FixSingleEquip</word>
<word>AddItem</word>
<word>DelItem</word>
<word>DelItemEx</word>
<word>ClearBag</word>
<word>ApplyEquip</word>
<word>ApplyEquipEx</word>
<word>DisableEquip</word>
<word>Player_MapMove</word>
<word>Player_MapMoveXY</word>
<word>ApplyItem</word>
<word>ApplyItemXY</word>
<word>ApplyItemTarget</word>
<word>DropItem</word>
<word>Player_RunScript</word>
<word>Player_TeamRunScript</word>
<word>Player_GuildRunScript</word>
<word>Player_IsPlayer</word>
<word>Player_GetItemGuid</word>
<word>Player_GetExpLimit</word>
<word>Player_GetAntiIndulge</word>
<word>Player_SetForbidTalk</word>
<word>Player_DisableForbidTalk</word>
<word>Player_Kick</word>
<word>Player_Catch</word>
<word>Player_Summon</word>
<word>Player_SetGhost</word>
<word>Player_SetInvincible</word>
<word>Player_RunGMCmd</word>
<word>ProgressBarStart</word>
<word>LoginTime</word>
<word>OnlineTime</word>
<word>OnlineTimeEx</word>
<word>LastLogoutTime</word>
<word>TotalTime</word>
<word>GenTeam</word>
<word>SetAutoReply</word>
<word>DisableAutoReply</word>
<word>SetOffline</word>
<word>IsOffline</word>
<word>HardwareCode</word>
<word>DelayCall</word>
<word>GiveItem</word>
<word>GiveBindItem</word>
<word>TakeItem</word>
<word>TakeItemEx</word>
<word>TakeOff</word>
<word>TakeOffEx</word>
<word>TakeOn</word>
<word>TakeOnEx</word>
<word>GiveOneItem</word>
<word>GiveOneBindItem</word>
<word>Monster_SetSeeker</word>
<word>Monster_GetMaster</word>
<word>MonsterKey2ID</word>
<word>Monster_IsExist</word>
<word>Monster_IsMonster</word>
<word>Monster_IsDie</word>
<word>Monster_Remove</word>
<word>Monster_GetEscapePoint</word>
<word>Monster_Escape</word>
<word>Monster_SpellTarget</word>
<word>Monster_GetAttackTarget</word>
<word>Monster_SetAttackTarget</word>
<word>Monster_GetSpecial</word>
<word>Npc_Remove</word>
<word>Npc_ChangeName</word>
<word>Npc_IsExist</word>
<word>AddShop</word>
<word>OpenShop</word>
<word>OpenWarehouse</word>
<word>OpenWarehouseAdv</word>
<word>NPCTalk</word>
<word>NPCTalkEx</word>
<word>NPCTalkDetail</word>
<word>NPCTalkDetailEx</word>
<word>Item_GetRole</word>
<word>Item_GetType</word>
<word>Item_GetSubType</word>
<word>Item_GetSite</word>
<word>Item_GetAmount</word>
<word>Item_SetAmount</word>
<word>Item_GetStack</word>
<word>Item_GetDurability</word>
<word>Item_GetMaxDurability</word>
<word>Item_SetDurability</word>
<word>Item_SetMaxDurability</word>
<word>Item_GetRepairCharge</word>
<word>Item_GetUsesCount</word>
<word>Item_SetUsesCount</word>
<word>Item_IsBind</word>
<word>Item_SetBind</word>
<word>Item_NotifyUpdate</word>
<word>Equip_GetIdentifyNum</word>
<word>Equip_GetIdentifyProp</word>
<word>Equip_SetIdentifyProp</word>
<word>Equip_GetRefineLevel</word>
<word>Equip_SetRefineLevel</word>
<word>Equip_GetRefineProp</word>
<word>Equip_SetRefineProp</word>
<word>Equip_GetLuckCurse</word>
<word>Equip_SetLuckCurse</word>
<word>Item_ChangeName</word>
<word>Item_Destroy</word>
<word>Equip_GetExtNum</word>
<word>Equip_GetExtProp</word>
<word>Equip_SetExtProp</word>
<word>Equip_SetQualProp</word>
<word>Equip_GetQualProp</word>
<word>ItemsByType</word>
<word>Item_GetLife</word>
<word>Item_SetLife</word>
<word>Item2Json</word>
<word>Json2Item</word>
<word>Json2ItemEx</word>
<word>CanFixEquip</word>
<word>Item_GetLevel</word>
<word>Item_GetIcon</word>
<word>ItemKey2ID</word>
<word>Item_DataRow</word>
<word>SendMail</word>
<word>Map_GetMapGuid</word>
<word>MapKey2ID</word>
<word>Map_GetWidth</word>
<word>Map_GetHeight</word>
<word>Map_GetPlayerCount</word>
<word>Map_GetMonsterCount</word>
<word>Map_GetRegionPlayers</word>
<word>Map_GetRegionMonsters</word>
<word>Map_GetRegionItems</word>
<word>Map_GenItem</word>
<word>Map_GenItemRnd</word>
<word>Map_BatchGenMonster</word>
<word>Map_GenMonster</word>
<word>Map_GenSingleMonster</word>
<word>Map_GenNpc</word>
<word>Map_GenNpcRnd</word>
<word>Map_ClearMonster</word>
<word>Map_ClearItem</word>
<word>Map_ClearNpc</word>
<word>Map_AddEffect</word>
<word>Map_IsInGS</word>
<word>Map_AddJumpPoint</word>
<word>Map_DelJumpPoint</word>
<word>Map_GetRegionNpcs</word>
<word>Map_GetMapNpc</word>
<word>Map_JumpXY</word>
<word>Map_JumpRnd</word>
<word>Map_CreateDgn</word>
<word>Map_DestroyDgn</word>
<word>Player_SetDgnTicket</word>
<word>Player_HasDgnTicket</word>
<word>Player_EnterDgn</word>
<word>Player_GetDgnByTicket</word>
<word>Map_ClearDgnPlayer</word>
<word>Map_ClearDgnMonster</word>
<word>Map_ClearDgnItem</word>
<word>Map_ClearDgnNpc</word>
<word>Map_IsDgnExist</word>
<word>IsFamilyAlly</word>
<word>IsInFamily</word>
<word>HasFamilyWar</word>
<word>GetRunningFamilyWar</word>
<word>NotifyRunningFamilyWar</word>
<word>CreateFamily</word>
<word>GetAllFamilys</word>
<word>GetFamilyJoinList</word>
<word>GetFamilyName</word>
<word>GetFamilyTitle</word>
<word>StartFamilyWar</word>
<word>GetAllCastle</word>
<word>HasCastle</word>
<word>IsCastleWarStart</word>
<word>StartCastleWar</word>
<word>StopCastleWar</word>
<word>HasCastleWar</word>
<word>GetCastleOwnFamily</word>
<word>SetCastleOwnFamily</word>
<word>GetCastleAttackFamily</word>
<word>GetCastleTempFamily</word>
<word>SetCastleTempFamily</word>
<word>SetCastleCustomVarInt</word>
<word>GetCastleCustomVarInt</word>
<word>SetCastleCustomVarStr</word>
<word>GetCastleCustomVarStr</word>
<word>GetCastleMapGuid</word>
<word>GetCastleBasiGuid</word>
<word>AddTitle</word>
<word>HasTitle</word>
<word>RemoveTitle</word>
<word>ApplyTitle</word>
<word>CanAcceptQuest</word>
<word>CanAccomplishQuest</word>
<word>AcceptQuest</word>
<word>AccomplishQuest</word>
<word>HasQuest</word>
<word>DropQuest</word>
<word>ForceAcceptQuest</word>
<word>ForceQuestReady</word>
<word>QuestRemainCount</word>
<word>GenEscorter</word>
<word>GenTraveler</word>
<word>IsEscorterDied</word>
<word>RemoveEscorter</word>
<word>GetEscorter</word>
<word>AddScheduled</word>
<word>DisableScheduled</word>
<word>JoinCamp</word>
<word>CampCount</word>
<word>CampCounts</word>
<word>CampInteg</word>
<word>CampIntegs</word>
<word>VerifyCampLevel</word>
<word>VerifyCampCount</word>
<word>IO_FileExists</word>
<word>IO_FileCTime</word>
<word>IO_FileMTime</word>
<word>IO_CreateTextFile</word>
<word>IO_EmptyTextFile</word>
<word>IO_GetFileText</word>
<word>IO_SetFileText</word>
<word>IO_AppendFile</word>
<word>IO_CheckTextInFile</word>
<word>IO_TextFileDeleteLineStr</word>
<word>IO_TextFileInsertLine</word>
<word>IO_TextFileDeleteLine</word>
<word>IO_TextFileGetLine</word>
<word>IO_TextFileRndGetLine</word>
<word>IO_TextFileCheckLine</word>
<word>IO_DirExists</word>
<word>IO_ForceDir</word>
<word>IO_GetLuaPath</word>
<word>IO_SetCustomVarInt</word>
<word>IO_GetCustomVarInt</word>
<word>IO_ClearCustomVarInt</word>
<word>IO_SetCustomVarStr</word>
<word>IO_GetCustomVarStr</word>
<word>IO_ClearCustomVarStr</word>
<word>on_item_appear</word>
<word>on_leave_map</word>
<word>on_enter_map</word>
<word>on_monster_disappear</word>
<word>on_monster_appear</word>
<word>on_map_destroy</word>
<word>on_map_create</word>
<word>on_gp</word>
<word>on_castle_war_init</word>
<word>on_castle_war_end</word>
<word>on_castle_war_start</word>
<word>on_logout</word>
<word>on_login</word>
<word>on_first_in_game</word>
<word>on_system_start</word>
<word>AddTrigger</word>
<word>HasTrigger</word>
<word>RemoveTrigger</word>
<word>ClearTrigger</word>
<word>SetTriggerFilters</word>
<word>AddTimerEx</word>
<word>DisableTimer</word>
<word>GSRunScript</word>
<word>GSTriggerScript</word>
<word>GenRandom</word>
<word>GetConstVar</word>
<word>ReloadConfig</word>
<word>ReloadGMList</word>
<word>ReloadScript</word>
<word>StrSplit</word>
<word>IsInCollection</word>
<word>GetSvrId</word>
<word>GetZoneId</word>
<word>GetGroupId</word>
<word>GetAgentId</word>
<word>GetZoneName</word>
<word>SkillKey2ID</word>
<word>BuffKey2ID</word>
<word>Mod</word>
<word>GetAllPlayerCount</word>
<word>RunClientScript</word>
<word>MapRndPos</word>
<word>GetTotalBill</word>
<word>SetFbdLogin</word>
<word>DisaFbdLogin</word>
<word>IsBanString</word>
<word>IsBanItem</word>
<word>MonstersByKey</word>
<word>GetURL</word>
<word>Base64Encode</word>
<word>Base64Decode</word>
<word>UrlEncode</word>
<word>UrlDecode</word>
<word>GenUniqueID</word>
<word>GetPlayerCount</word>
<word>GetVipRemain</word>
<word>GetVipLevelRemain</word>
<word>GetVipLevel</word>
<word>SetVipLevel</word>
<word>ShowFormWithContent</word>
<word>Str2Time</word>
<word>SysMsg_SendWarnMsg</word>
<word>SysWarnMsg</word>
<word>SysMsg_SendPromptMsg</word>
<word>SysPromptMsg</word>
<word>SysMsg_SendTriggerMsg</word>
<word>SysTriggerMsg</word>
<word>SysMsg_SendInputDlg</word>
<word>InputDlgEx</word>
<word>SysMsg_SendMsgDlg</word>
<word>SysMsg_SendWebMsg</word>
<word>WebBoxEx</word>
<word>SysMsg_SendWebPage</word>
<word>WebBrowser</word>
<word>Hp</word>
<word>GUID</word>
<word>Mp</word>
<word>PhyAtk</word>
<word>TaoAtk</word>
<word>MagAtk</word>
<word>on_item_disappear</word>
<word>on_npc_appear</word>
<word>on_npc_disappear</word>
<word>on_level_up</word>
<word>on_pre_equip</word>
<word>on_post_equip</word>
<word>on_pre_un_equip</word>
<word>on_post_un_equip</word>
<word>on_move</word>
<word>on_pre_spell</word>
<word>on_spell</word>
<word>on_pre_mining</word>
<word>on_mining</word>
<word>on_pre_item_apply</word>
<word>on_item_apply</word>
<word>on_pre_item_pickup</word>
<word>on_item_pickup</word>
<word>on_pre_item_drop</word>
<word>on_item_drop</word>
<word>on_pre_die</word>
<word>on_post_die</word>
<word>on_kill</word>
<word>on_attack</word>
<word>on_damage_process</word>
<word>on_restore_process</word>
<word>on_teleport</word>
<word>on_pre_catch</word>
<word>on_catch</word>
<word>on_pre_dig_meat</word>
<word>on_add_buff</word>
<word>on_remove_buff</word>
<word>on_pre_drop</word>
<word>on_post_drop</word>
<word>on_pre_drop_one</word>
<word>on_post_drop_one</word>
<word>on_add_skill</word>
<word>on_switch_skill</word>
<word>on_summon</word>
<word>on_pre_process_pk</word>
<word>on_post_process_pk</word>
<word>on_create</word>
<word>on_destroy</word>
<word>on_pre_enter_jump</word>
<word>on_equip_suit</word>
<word>on_un_equip_suit</word>
<word>on_item_amount_zero</word>
<word>on_item_use_zero</word>
<word>on_item_dur_zero</word>
<word>on_item_timeup</word>
<word>on_add_exp</word>
<word>on_player_relive</word>
<word>on_dungeon_end</word>
<word>SetDBNum</word>
<word>GetDBNum</word>
<word>SetDBStr</word>
<word>GetDBStr</word>
<word>SetDBNumEx</word>
<word>SetDBStrEx</word>
<word>GridAttr</word>
<word>Player_SetServantLevel</word>
<word>Player_IsAntiIndulge</word>
<word>on_billin</word>
<word>on_mall</word>
<word>DelSkill</word>
<word>DelAllSkill</word>
<word>GenTimerId</word>
<word>Map_BatchGenCampMonster</word>
<word>Map_GenCampMonster</word>
<word>Map_GenSingleCampMonster</word>
<word>KickByName</word>
<word>Achievement</word>
<word>AddAvataBuff</word>
<word>AddBindGold</word>
<word>AddBindIngot</word>
<word>AddExp</word>
<word>AddGold</word>
<word>AddIngot</word>
<word>AddIntegral</word>
<word>AddSingleItem</word>
<word>AddTimer</word>
<word>Amulet</word>
<word>AntiIndulgeExpire</word>
<word>Armor</word>
<word>Attr</word>
<word>Brawn</word>
<word>ClearTimer</word>
<word>CreateHeroForPlayer</word>
<word>DeleteHeroForPlayer</word>
<word>DelUnmatchedSkill</word>
<word>DestroyDummy</word>
<word>Dir</word>
<word>Energy</word>
<word>EquipWeight</word>
<word>FindFirstBagFreeSlot</word>
<word>Gem</word>
<word>Gender</word>
<word>GenDummy</word>
<word>GenHeroForPlayer</word>
<word>GetActiveCount</word>
<word>GetActiveCountToday</word>
<word>GetBagFree</word>
<word>GetBagFreeEx</word>
<word>GetBagSize</word>
<word>GetBagSizeEx</word>
<word>GetBindGold</word>
<word>GetBindIngot</word>
<word>GetBuffTime</word>
<word>GetDayInt</word>
<word>GetDayStr</word>
<word>GetDynamicAttr</word>
<word>GetExp</word>
<word>GetFamilyCastles</word>
<word>GetFamilyMembers</word>
<word>GetGold</word>
<word>GetIngot</word>
<word>GetIntegral</word>
<word>GetItemsByKeys</word>
<word>GetLocalTime</word>
<word>GetLuaPerformance</word>
<word>GetPlayerCurrentHeroList</word>
<word>GetPlayerHeroList</word>
<word>GetQuestAccomplishing</word>
<word>GetQuestProgressing</word>
<word>GetTickCount</word>
<word>GetTime</word>
<word>GetTitle</word>
<word>GetWeekInt</word>
<word>GetWeekStr</word>
<word>GMLevel</word>
<word>God</word>
<word>Hair</word>
<word>HairColor</word>
<word>HasFamily</word>
<word>Head</word>
<word>Helmet</word>
<word>HpPoint</word>
<word>IO_DeleteDir</word>
<word>IO_DeleteFile</word>
<word>IO_GetFileString</word>
<word>IsAntiIndulge</word>
<word>IsCastleWarNull</word>
<word>IsInRegion</word>
<word>Item_GetBySite</word>
<word>Item_GetCustomVarInt</word>
<word>Item_GetCustomVarStr</word>
<word>Item_GetID</word>
<word>Item_GetKeyName</word>
<word>Item_GetName</word>
<word>Item_GetPosX</word>
<word>Item_GetPosY</word>
<word>Item_IsTimeLimit</word>
<word>Item_NotifyCustomParam</word>
<word>Item_SetCustomVarInt</word>
<word>Item_SetCustomVarStr</word>
<word>ItemCount</word>
<word>ItemCountEx</word>
<word>ItemDropFreezeTime</word>
<word>ItemDropHost</word>
<word>ItemDropTime</word>
<word>ItemDropType</word>
<word>ItemKeyName</word>
<word>ItemRole</word>
<word>Job</word>
<word>JuJu</word>
<word>LastAtkTime</word>
<word>LastMoveTime</word>
<word>LastTalkTime</word>
<word>LeaveTeam</word>
<word>Level</word>
<word>LockSwitch</word>
<word>Log</word>
<word>LogDetail</word>
<word>LogDetailWithId</word>
<word>LogWithId</word>
<word>LuckCurse</word>
<word>MagAtkPoint</word>
<word>MagDef</word>
<word>MagDefPoint</word>
<word>Mail</word>
<word>MailJsonItem</word>
<word>MailToPlayer</word>
<word>Map_GenGold</word>
<word>Map_GenItemEx</word>
<word>Map_GetCustomVarInt</word>
<word>Map_GetCustomVarStr</word>
<word>Map_GetDistance</word>
<word>Map_GetGridObjList</word>
<word>Map_GetMapKeyName</word>
<word>Map_GetMapName</word>
<word>Map_GetMapPlayers</word>
<word>Map_RemoveMonster</word>
<word>Map_RemoveNpc</word>
<word>Map_SetCustomVarInt</word>
<word>Map_SetCustomVarStr</word>
<word>Map_SetOffTimer</word>
<word>Map_SetOnTimer</word>
<word>MapCanRide</word>
<word>MapKeyName</word>
<word>MD5</word>
<word>Medal</word>
<word>Meritor</word>
<word>ModifyItemGold</word>
<word>Monster_AddBuff</word>
<word>Monster_DataRow</word>
<word>Monster_DelBuff</word>
<word>Monster_GetCurTarget</word>
<word>Monster_GetCustomVarInt</word>
<word>Monster_GetCustomVarStr</word>
<word>Monster_GetDropOwner</word>
<word>Monster_GetHateList</word>
<word>Monster_GetIntProp</word>
<word>Monster_GetKeyName</word>
<word>Monster_GetMap</word>
<word>Monster_GetPosX</word>
<word>Monster_GetPosY</word>
<word>Monster_IsHasBuff</word>
<word>Monster_JumpXY</word>
<word>Monster_Kill</word>
<word>Monster_SetCustomVarInt</word>
<word>Monster_SetCustomVarStr</word>
<word>Monster_SetPanelSize</word>
<word>Monster_SpellTargetEx</word>
<word>Monster_Type</word>
<word>Mount</word>
<word>MpPoint</word>
<word>Necklace</word>
<word>Now</word>
<word>Npc_GetCustomVar</word>
<word>Npc_GetKeyName</word>
<word>Npc_GetPosX</word>
<word>Npc_GetPosY</word>
<word>Npc_SetCustomVar</word>
<word>Npc_SetPanelSize</word>
<word>OnGloryTrigger</word>
<word>PhyAtkPoint</word>
<word>PhyDef</word>
<word>PhyDefPoint</word>
<word>Pk</word>
<word>Player_AddBuff</word>
<word>Player_AddSkill</word>
<word>Player_ChangeGender</word>
<word>Player_ChangeJob</word>
<word>Player_ClearBag</word>
<word>Player_DelBuff</word>
<word>Player_DestroyItem</word>
<word>Player_DestroyItemBind</word>
<word>Player_DestroyItemUnbind</word>
<word>Player_DropItem</word>
<word>Player_DropItemEx</word>
<word>Player_GetBagFree</word>
<word>Player_GetBagItemList</word>
<word>Player_GetBagSize</word>
<word>Player_GetCustomVarInt</word>
<word>Player_GetCustomVarStr</word>
<word>Player_GetDir</word>
<word>Player_GetDistance</word>
<word>Player_GetEquipGuid</word>
<word>Player_GetEquipName</word>
<word>Player_GetGuid</word>
<word>Player_GetGuidProp</word>
<word>Player_GetIntProp</word>
<word>Player_GetItemCount</word>
<word>Player_GetItemCountBind</word>
<word>Player_GetItemCountUnbind</word>
<word>Player_GetPosX</word>
<word>Player_GetPosY</word>
<word>Player_GetStrProp</word>
<word>Player_GetTimeProp</word>
<word>Player_GetWarehouseFree</word>
<word>Player_GetWarehouseItemCount</word>
<word>Player_GetWarehouseItemCountBind</word>
<word>Player_GetWarehouseItemCountUnbind</word>
<word>Player_GetWarehouseSize</word>
<word>Player_GiveItemBind</word>
<word>Player_GiveItemUnbind</word>
<word>Player_GiveSingleItem</word>
<word>Player_GoHome</word>
<word>Player_IsCanAttack</word>
<word>Player_IsCanMove</word>
<word>Player_IsCanNpcTalk</word>
<word>Player_IsCanSpell</word>
<word>Player_IsCanTalk</word>
<word>Player_IsCanTurn</word>
<word>Player_IsCanUseItem</word>
<word>Player_IsDie</word>
<word>Player_IsHasBuff</word>
<word>Player_IsHasSkill</word>
<word>Player_IsInGS</word>
<word>Player_IsOnline</word>
<word>Player_ItemRequest</word>
<word>Player_Kill</word>
<word>Player_KillServant</word>
<word>Player_NotifyCustomParam</word>
<word>Player_NpcMove</word>
<word>Player_SetAlias</word>
<word>Player_SetCustomVarInt</word>
<word>Player_SetCustomVarStr</word>
<word>Player_SetIntProp</word>
<word>Player_UseItem</word>
<word>Player_UseItemByID</word>
<word>PostDBEvt</word>
<word>PostURL</word>
<word>Prestige</word>
<word>Random</word>
<word>RemainPoint</word>
<word>Ride</word>
<word>Ring</word>
<word>ScriptFuncToPlayer</word>
<word>ScriptTextToPlayer</word>
<word>SetAchievement</word>
<word>SetAutoOpt</word>
<word>SetBrawn</word>
<word>SetDayInt</word>
<word>SetDayStr</word>
<word>SetDir</word>
<word>SetDynamicAttr</word>
<word>SetEnergy</word>
<word>SetEquipWeight</word>
<word>SetGender</word>
<word>SetHair</word>
<word>SetHairColor</word>
<word>SetHead</word>
<word>SetHeroState</word>
<word>SetHp</word>
<word>SetHpPoint</word>
<word>SetJob</word>
<word>SetLevel</word>
<word>SetLockSwitch</word>
<word>SetLuckCurse</word>
<word>SetMagAtk</word>
<word>SetMagAtkPoint</word>
<word>SetMagDef</word>
<word>SetMagDefPoint</word>
<word>SetMeritor</word>
<word>SetMp</word>
<word>SetMpPoint</word>
<word>SetNetCheck</word>
<word>SetPhyAtk</word>
<word>SetPhyAtkPoint</word>
<word>SetPhyDef</word>
<word>SetPhyDefPoint</word>
<word>SetPk</word>
<word>SetPrestige</word>
<word>SetRemainPoint</word>
<word>SetTaoAtk</word>
<word>SetTaoAtkPoint</word>
<word>SetWeekInt</word>
<word>SetWeekStr</word>
<word>SetWeight</word>
<word>Shoes</word>
<word>Shoulder</word>
<word>ShowForm</word>
<word>StartAutoRun</word>
<word>StartCastleWarEx</word>
<word>StartStall</word>
<word>StopAutoRun</word>
<word>StopStall</word>
<word>SubBindGold</word>
<word>SubBindIngot</word>
<word>SubExp</word>
<word>SubGold</word>
<word>SubIngot</word>
<word>SubIntegral</word>
<word>SysCenterMsg</word>
<word>SysGuildMsg</word>
<word>SysMapMsg</word>
<word>SysMsg_SendBoardMsg</word>
<word>SysMsg_SendTipsMsg</word>
<word>SysRoleTalk</word>
<word>SysTipsMsg</word>
<word>SysTopMsg</word>
<word>TaoAtkPoint</word>
<word>TimeDiff</word>
<word>TitleName</word>
<word>ToAttrName</word>
<word>UnRide</word>
<word>UserID</word>
<word>VarList</word>
<word>Weapon</word>
<word>Weight</word>
<word>Wings</word>
<word>Wrist</word>
<word>GetDeposit</word>
<word>GUIDType</word>
<word>ModifyCastleAttacks</word>
<word>ModifyCastleStart</word>
<word>QueryCastleStart</word>
<word>AddDeposit</word>
<word>SubDeposit</word>
<word>SetFormAllowFunc</word>
<word>GetRegionFree</word>
<word>NotifyCSChannelMsg</word>
<word>GetRegionFreeRnd</word>
<word>on_add_exp_all</word>
<word>on_attack_ex</word>
<word>on_dig_meat</word>
<word>on_monster_born</word>
<word>on_pre_logout</word>
<word>on_pre_mall</word>
<word>on_ride_request</word>
<word>on_system_stop</word>
<word>on_timer_check</word>
<word>on_unride_request</word>
<word>post_die</word>
<word>post_monster_die</word>
<word>post_player_die</word>
<word>post_process_pk</word>
<word>pre_die</word>
<word>pre_monster_die</word>
<word>pre_player_die</word>
<word>pre_player_relive</word>
<word>pre_process_pk</word>
<word>AllServantBetry</word>
<word>GetRegionFreeEx</word>
<word>GetRegionFreeRndEx</word>
<word>GetTempInt</word>
<word>GetTempStr</word>
<word>HasItem</word>
<word>InAdvWarehouse</word>
<word>InBag</word>
<word>InEquip</word>
<word>InWarehouse</word>
<word>Map_GetRegionItemsEx</word>
<word>Map_GetRegionMonstersEx</word>
<word>Map_GetRegionNpcsEx</word>
<word>Map_GetRegionPlayersEx</word>
<word>MoveItem</word>
<word>SendSpeakerMsg</word>
<word>ServantBetry</word>
<word>SetTempInt</word>
<word>SetTempStr</word>
<word>eRoleAttr</word>
<word>eRoleSite</word>
<word>eTriggerType</word>
<word>string.trim</word>
<word>string.split</word>
<word>string.indexOf</word>
<word>string.indexOf</word>
<word>string.left</word>
<word>string.left</word>
<word>string.right</word>
<word>string.right</word>
<word>string.mid</word>
<word>string.ord</word>
<word>string.chr</word>
<word>string.replace</word>
<word>json.encode</word>
<word>json.decode</word>
<word>GetItemGold</word>
<word>SetDummyDefaultSkillAI</word>
<word>SetDummySkillAI</word>
<word>GetZoneKey</word>
<word>SetLog</word>
<word>on_escorter_fail</word>
<word>on_escorter_far</word>
<word>GetCurScriptName</word>
<word>GetSvrRunTime</word>
<word>SetDBMerge</word>
<word>SetScriptTimeout</word>
<word>Player_SetNameColor</word>
<word>AddTitleEx</word>
<word>GetHeroRage</word>
<word>MapOwnerFamily</word>
<word>Player_GetServantLevel</word>
<word>SetHeroRage</word>
<word>on_monster_in_fight</word>
<word>on_monster_out_fight</word>
<word>on_post_monster_die</word>
<word>on_post_player_die</word>
<word>on_pre_monster_die</word>
<word>on_pre_player_die</word>
<word>on_pre_player_relive</word>
<word>Item_IsExist</word>
<word>Item_MapRemove</word>
<word>Map_GetRegionDummys</word>
<word>SetDummyAIOption</word>
<word>SetDummyDefaultAIOption</word>
<word>Str2Zip</word>
<word>Zip2Str</word>
<word>GetHeroLord</word>
<word>Monster_ClearHateList</word>
<word>Monster_SetHateList</word>
<word>on_pre_curse</word>
<word>on_pre_harm</word>
<word>GetGroupName</word>
<word>HasZhenshi</word>
<word>RoleRankTop</word>
<word>on_apply_buff</word>
<word>SetNetCheckEx</word>
<word>on_npc_buy</word>
<word>on_pre_npc_buy</word>
<word>GetPlayerUUID</word>
<word>UUIDToGUID</word>
<word>GetCurrentHero</word>
<word>ShowRoleHPRef</word>
<word>GetFamilyByName</word>
<word>Map_GetRegionMonstersCount</word>
<word>IsBagLock</word>
<word>SetBagLock</word>
<word>SetFamilyMaxMember</word>
<word>CopyHero</word>
<word>Player_SpellGrid</word>
<word>Player_SpellTarget</word>
<word>SysSpeakMsg</word>
<word>GetFamilyLeader</word>
<word>GetFamilyMembersByTitleId</word>
<word>GetBuffAtt1</word>
<word>GetHeroCopyNum</word>
<word>IsHeroCopy</word>
<word>ShowRoleHPRefEx</word>
<word>FlushPlayerData</word>
<word>GetCopyWho</word>
<word>KillEx</word>
<word>SetDummyState</word>
<word>HasTimer</word>
<word>GetJoinHitTarget</word>
<word>CancelStall</word>
<word>LoadPlayer</word>
<word>on_hack_check</word>
<word>on_pre_stall</word>
<word>AddFamilyMember</word>
<word>ChangeFamilyTitle</word>
<word>DelFamilyMember</word>
<word>Player_SpellPosX</word>
<word>Player_SpellPosY</word>
<word>on_auto_add_gold</word>
<word>GetClientVer</word>
<word>Map_AddJumpPointEx</word>
<word>on_hack_check2</word>
<word>GetSkillExp</word>
<word>SetSkillExp</word>
<word>on_fang_chen_mi</word>
<word>SetServantMasterName</word>
<word>Guid2Id</word>
<word>Id2KeyName</word>
<word>KeyName2Id</word>
<word>KeyName2Name</word>
<word>Player_SetAttackModeLock</word>
<word>on_family_member_ntf</word>
<word>Guid2Name</word>
<word>DummyLockTarget</word>
<word>DummyMove</word>
<word>GetBuffList</word>
<word>LastKeepPkgTime</word>
<word>GetFamilyMemberAttr</word>
<word>Player_AddEffect</word>
<word>LoadPlayerEx</word>
<word>on_pre_stall_buy</word>
<word>TeamInvite</word>
<word>NPCTalkDetailQuest</word>
<word>Player_IsAttackModeLock</word>
<word>GetGSClientVer</word>
<word>GetClientVerEx</word>
<word>RequestClientVer</word>
<word>IO_TextFileTotalLine</word>
<word>Player_CatchEx</word>
<word>on_family_ntf</word>
<word>CanAttack</word>
<word>SetIsBrust</word>
<word>IO_FileList</word>
<word>IO_FileSize</word>
<word>on_item_dur_zero_ex</word>
<word>on_post_dummy_die</word>
<word>on_pre_dummy_die</word>
<word>GetEquipSuitCount</word>
<word>on_item_attr_zero</word>
<word>SetServantPickItem</word>
<word>SetServantPickList</word>
