package script
{
	public class GameEventDefine
	{
		var LUA_EVENT_NONE 						= 0;
		var LUA_EVENT_ONPLAYLEVELUP 			= 0;
		var LUA_EVENT_ONLOGIN 					= 0;
		var LUA_EVENT_INITRESCOMPLETE 			= 0;
		var LUA_EVENT_ONENTERMAP 				= 0;
		var LUA_EVENT_ONADDSKILL 				= 0;
		var LUA_EVENT_ONADDITEM 				= 0;
		var LUA_EVENT_ONDROPITEM 				= 0;
		var LUA_EVENT_CHANGEATTACMODE 			= 0;
		var LUA_EVENT_GETNEWQUEST 				= 0;
		var LUA_EVENT_FINISHQUEST 				= 0;
		var LUA_EVENT_READYQUEST 				= 0;
		var LUA_EVENT_DROPQUEST 				= 0;
		var LUA_EVENT_ONADDBUFF 				= 0;
		var LUA_EVENT_ONPLAYERAPPEAR 			= 0;
		var LUA_EVENT_ONFINISHMASTER 			= 0;
		var LUA_EVENT_ONFINISHMARRY 			= 0;
		var LUA_EVENT_ONJOINFAMILY 				= 0;
		var LUA_EVENT_ONLEAVEFAMILY 			= 0;
		var LUA_EVENT_ONACHIEVECASTLE 			= 0;
		var LUA_EVENT_ONLOSECASTLE 				= 0;
		var LUA_EVENT_ONNEWMAIL 				= 0;
		var LUA_EVENT_ONADDFRIEND 				= 0;
		var LUA_EVENT_ONDELFRIEND 				= 0;
		var LUA_EVENT_ONJOINTEAM 				= 0;
		var LUA_EVENT_ONLEAVETEAM 				= 0;
		var LUA_EVENT_ONP2PTRADEOK 				= 0;
		var LUA_EVENT_OPENPAKAGEGUI 			= 0;
		var LUA_EVENT_OPENSKILLGUI 				= 0;
		var LUA_EVENT_OPENROLEGUI 				= 0;
		var LUA_EVENT_OPENMAILGUI 				= 0;
		var LUA_EVENT_OPENQUESTGUI 				= 0;
		var LUA_EVENT_OPENSYSSETGUI 			= 0;
		var LUA_EVENT_OPENFAMILYGUI 			= 0;
		var LUA_EVENT_OPENVIPGUI 				= 0;
		var LUA_EVENT_OPENRANKGUI 				= 0;
		var LUA_EVENT_OPENFRIENDGUI 			= 0;
		var LUA_EVENT_OPENBIGMAPGUI 			= 0;
		var LUA_EVENT_OPENBIGCAMPAIGNGUI 		= 0;
		var LUA_EVENT_OPENWAREHOUSEGUI 			= 0;
		var LUA_EVENT_OPENADVWAREHOUSEGUI 		= 0;
		var LUA_EVENT_OPENGAMEMALLGUI 			= 0;
		var LUA_EVENT_OPENGAMESETTINGGUI 		= 0;
		var LUA_EVENT_PROPERTYDATA 				= 0;
		var LUA_EVENT_CLOSEQUESTGUI 			= 0;
		var LUA_EVENT_CLOSEPACKAGEGUI 			= 0;
		var LUA_EVENT_CLOSEROLEGUI 				= 0;
		var LUA_EVENT_CLOSESKILLGUI 			= 0;
		var LUA_EVENT_ONAPPLYITEM 				= 0;
		var LUA_EVENT_ONTEAMINVITE 				= 0;
		var LUA_EVENT_UPDATASCREENSIZE 			= 0;
		var LUA_EVENT_ONQUITEGAME 				= 0;
		var LUA_EVENT_ONSHOWFORM 				= 0;
		var LUA_EVENT_SUBMITFORMACK 			= 0;
		var LUA_EVENT_RELOADLUAEND 				= 0;
		var LUA_EVENT_ONGUIDECREATE 			= 0;
		var LUA_EVENT_ONEQUIPMENT 				= 0;
		var LUA_EVENT_HORSEBUTTONCLICK 			= 0;
		var LUA_EVENT_WNDLOADLAYOUT 			= 0;
		var LUA_EVENT_ITEMWNDMOVEITEMIN 		= 0;
		var LUA_EVENT_OPENNPCTALK 				= 0;
		var LUA_EVENT_CLICKNPCTALKITEM 			= 0;
		var LUA_EVENT_CLICKTASKMAPLINK 			= 0;
		var LUA_EVENT_CLICKTASKNPCLINK 			= 0;
		var LUA_EVENT_DEFENDICONINIT 			= 0;
		var LUA_EVENT_UILINK 					= 0;
		var LUA_EVENT_ONITEMUPDATE 				= 0;
		var LUA_EVENT_ONITEMATTRCHANGE 			= 0;
		var LUA_EVENT_ONITEMDESTROY 			= 0;
		var LUA_EVENT_ONUISTYLECHANGE 			= 0;
		var LUA_EVENT_ONHEROCREATE 				= 0;
		var LUA_EVENT_ONHERODESTROY 			= 0;
		var LUA_EVENT_ONMOUSEITEMCLEAR 			= 0;
		var LUA_EVENT_OFFEQUIPMENT 				= 0;
		var LUA_EVENT_AUTOATTACSTOP 			= 0;
		var LUA_EVENT_PLAYERADDBUFF 			= 0;
		var LUA_EVENT_PLAYERDESTORYBUFF 		= 0;
		var LUA_EVENT_HEROADDBUFF 				= 0;
		var LUA_EVENT_HERODESTORYBUFF 			= 0;
		var LUA_EVENT_HERO_CHANGESTATE 			= 0;
		var LUA_EVENT_ONHEROADDITEM 			= 0;
		var LUA_EVENT_PLAYERATTREXTREF 			= 0;
		var LUA_EVENT_HEROATTREXTREF 			= 0;
		var LUA_EVENT_PLAYERERRORCODE 			= 0;
		var LUA_EVENT_HEROERRORCODE 			= 0;
		var LUA_EVENT_SHIELDREMOVE 				= 0;
		var LUA_EVENT_INATHLETICSREGION 		= 0;
		var LUA_EVENT_OUTATHLETICSREGION 		= 0;
		var LUA_EVENT_INITMAININTERFACE 		= 0;
		var LUA_EVENT_SWITICHSKILLACTIVE 		= 0;
		var LUA_EVENT_STALLSELL 				= 0;
		var LUA_EVENT_ITEMCTRLIN 				= 0;
		var LUA_EVENT_ITEMCTRLOUT 				= 0;
		var LUA_EVENT_CUSTOMDATALOAD 			= 0;
		var LUA_EVENT_OPENHEROGUI 				= 0;
		var LUA_EVENT_OPENHEROPACKAGE 			= 0;
		var LUA_EVENT_OPENDESKWINODW 			= 0;
		var LUA_EVENT_CHATCHANNELCHANGE 		= 0;
		var LUA_EVENT_UPDATAMALLITEM 			= 0;
		var LUA_EVENT_PROPERTYDATA64 			= 0;
		var LUA_EVENT_CHOOSEPLAYER 				= 0;
		var LUA_EVENT_HIDECHOOSEPLAYER 			= 0;
		var LUA_EVENT_PACKAGECOUNT 				= 0;
		var LUA_EVENT_SKILLPROFICIENCY 			= 0;
		var LUA_EVENT_P2PINVITE 				= 0;
		var LUA_EVENT_P2PLOCK 					= 0;
		var LUA_EVENT_STALLSETPRICE 			= 0;
		var LUA_EVENT_VISITSTALLLIST 			= 0;
		var LUA_EVENT_HIDEVISITSTALL 			= 0;
		var LUA_EVENT_VISITSTALLBUY 			= 0;
		var LUA_EVENT_TRANSFERLEADERTEAM 		= 0;
		var LUA_EVENT_DISMISSTEAM 				= 0;
		var LUA_EVENT_OPENTEAM 					= 0;
		var LUA_EVENT_CLOSETEAM 				= 0;
		var LUA_EVENT_ONCHANGEFRIEND 			= 0;
		var LUA_EVENT_ONFINISHACHIVE 			= 0;
		var LUA_EVENT_ONACHIVELIST 				= 0;
		var LUA_EVENT_JOINTEAM 					= 0;
		var LUA_EVENT_CLOSESYSSETGUI 			= 0;
		var LUA_EVENT_MAILLIST 					= 0;
		var LUA_EVENT_MAILDETAIL 				= 0;
		var LUA_EVENT_MAILATTACHMENTOK 			= 0;
		var LUA_EVENT_NPCQUEST 					= 0;
		var LUA_EVENT_FAMILYINVITE 				= 0;
		var LUA_EVENT_FAMILYINVITENOTICE 		= 0;
		var LUA_EVENT_QUICKCHANGE 				= 0;
		var LUA_EVENT_STARTSTALL 				= 0;
		var LUA_EVENT_OTHERROLEDATA 			= 0;
		var LUA_EVENT_OPENTRADEGUI 				= 0;
		var LUA_EVENT_OPENSTALLGUI 				= 0;
		var LUA_EVENT_CLOSEGAMEMALLGUI 			= 0;
		var LUA_EVENT_CLOSEWAREHOUSEGUI 		= 0;
		var LUA_EVENT_CLOSEADVWAREHOUSEGUI 		= 0;
		var LUA_EVENT_CLOSETRADEGUI 			= 0;
		var LUA_EVENT_CLOSESTALLGUI 			= 0;
		var LUA_EVENT_CAMPAIGNLIST 				= 0;
		var LUA_EVENT_FAMILYNOTICECONFIRM 		= 0;
		var LUA_EVENT_ONLEAVETEAMEX 			= 0;
		var LUA_EVENT_ONJOINTEAMEX 				= 0;
		var LUA_EVENT_SKIllAPPLY 				= 0;
		var LUA_EVENT_CALLBACKCOUNTCHANGE 		= 0;
		var LUA_EVENT_SETTINGPROPCHANGE 		= 0;
		var LUA_EVENT_OBJDISPEAR 				= 0;
		var LUA_EVENT_PROPERTYDATALIST 			= 0;
		var LUA_EVENT_AUTOMOVEEND 				= 0;
		var LUA_EVENT_OTHERPLAYERINFO 			= 0;
		var LUA_EVENT_COUNT 					= 0;
		var EVENT_DEFAULT_TAG 					= "";

		public function GameEventDefine()
		{
			//事件定义
			var i = 0;
			LUA_EVENT_NONE = i; i=i+1;				//()
			LUA_EVENT_ONPLAYLEVELUP = i; i=i+1;	  	//玩家等级提升(INT _Level)
			LUA_EVENT_ONLOGIN = i; i=i+1;		 		//登录()
			LUA_EVENT_INITRESCOMPLETE = i; i=i+1;		//窗口创建完毕()
			LUA_EVENT_ONENTERMAP = i; i=i+1;	 		//进入地图(string _MapKeyName INT _XPos INT _YPos)
			LUA_EVENT_ONADDSKILL = i; i=i+1;			//添加技能(INT _SkillID)
			LUA_EVENT_ONADDITEM = i; i=i+1; 			//添加物品(string _ItemName,UINT64 _ItemGUID,INT _ItemID)
			LUA_EVENT_ONDROPITEM = i; i=i+1; 			//丢弃物品(string _ItemName,UINT64 _ItemGUID,INT _ItemID)
			LUA_EVENT_CHANGEATTACMODE = i; i=i+1; 	//切换攻击模式(INT _AttacMode)
			LUA_EVENT_GETNEWQUEST = i; i=i+1; 		//接取任务(INT _QuestID)
			LUA_EVENT_FINISHQUEST = i; i=i+1; 		//完成任务(INT _QuestID)
			LUA_EVENT_READYQUEST = i; i=i+1; 			//激活任务(INT _QuestID)
			LUA_EVENT_DROPQUEST = i; i=i+1;			//放弃任务(INT _QuestID)
			LUA_EVENT_ONADDBUFF = i; i=i+1; 			//添加buff(INT _BuffID)
			LUA_EVENT_ONPLAYERAPPEAR = i; i=i+1;		//玩家出现(UINT64 _RoleID)
			LUA_EVENT_ONFINISHMASTER = i; i=i+1;		//拜师完成()
			LUA_EVENT_ONFINISHMARRY = i; i=i+1;		//结婚完成()
			LUA_EVENT_ONJOINFAMILY = i; i=i+1;		//加入行会()
			LUA_EVENT_ONLEAVEFAMILY = i; i=i+1;		//离开行会()
			LUA_EVENT_ONACHIEVECASTLE = i; i=i+1;		//获得城堡()
			LUA_EVENT_ONLOSECASTLE = i; i=i+1;		//关闭城堡()
			LUA_EVENT_ONNEWMAIL = i; i=i+1;			//新邮件提醒()
			LUA_EVENT_ONADDFRIEND = i; i=i+1;			//添加好友()
			LUA_EVENT_ONDELFRIEND = i; i=i+1;			//删除好友()
			LUA_EVENT_ONJOINTEAM = i; i=i+1;			//加入队伍()
			LUA_EVENT_ONLEAVETEAM = i; i=i+1;			//离开队伍()
			LUA_EVENT_ONP2PTRADEOK = i; i=i+1;		//交易()
			LUA_EVENT_OPENPAKAGEGUI = i; i=i+1;		//打开包裹()
			LUA_EVENT_OPENSKILLGUI = i; i=i+1;		//打开技能面板()
			LUA_EVENT_OPENROLEGUI = i; i=i+1;			//打开角色面板()
			LUA_EVENT_OPENMAILGUI = i; i=i+1;			//打开邮件()
			LUA_EVENT_OPENQUESTGUI = i; i=i+1;		//打开任务面板()
			LUA_EVENT_OPENSYSSETGUI = i; i=i+1;		//打开设置面板()
			LUA_EVENT_OPENFAMILYGUI = i; i=i+1;		//打开行会面板()
			LUA_EVENT_OPENVIPGUI = i; i=i+1;			//打开VIP面板()
			LUA_EVENT_OPENRANKGUI = i; i=i+1;			//打开排行榜面板()
			LUA_EVENT_OPENFRIENDGUI = i; i=i+1;		//打开好友面板()
			LUA_EVENT_OPENBIGMAPGUI = i; i=i+1;		//打开大地图面板()
			LUA_EVENT_OPENBIGCAMPAIGNGUI = i; i=i+1;	//打开活动面板()
			LUA_EVENT_OPENWAREHOUSEGUI = i; i=i+1;	//打开仓库面板()
			LUA_EVENT_OPENADVWAREHOUSEGUI = i; i=i+1;	//打开高级仓库面板()
			LUA_EVENT_OPENGAMEMALLGUI = i; i=i+1;		//打开商城面板()
			LUA_EVENT_OPENGAMESETTINGGUI = i; i=i+1;	//打开游戏设置面板()
			LUA_EVENT_PROPERTYDATA = i; i=i+1;		//角色属性改变(UINT64 _RoleID, INT _Type, INT _Data)
			LUA_EVENT_CLOSEQUESTGUI = i; i=i+1;		//关闭任务窗口()
			LUA_EVENT_CLOSEPACKAGEGUI = i; i=i+1;		//关闭包裹窗口()
			LUA_EVENT_CLOSEROLEGUI = i; i=i+1;		//关闭角色面板()
			LUA_EVENT_CLOSESKILLGUI = i; i=i+1;		//关闭技能面板()
			LUA_EVENT_ONAPPLYITEM = i; i=i+1;			//使用物品(string _ItemName,UINT64 _ItemGUID,INT _ItemID)
			LUA_EVENT_ONTEAMINVITE = i; i=i+1;		//被邀请组队()
			LUA_EVENT_UPDATASCREENSIZE = i; i=i+1;	//窗口大小改变时调用(INT_XDiff,INT_YDiff)
			LUA_EVENT_ONQUITEGAME = i; i=i+1;			//登出时调用()
			LUA_EVENT_ONSHOWFORM = i; i=i+1;			//接收到表单(string _FormName, string _FormContent)
			LUA_EVENT_SUBMITFORMACK = i; i=i+1;		//提交表单反馈(string _ScriptName, string _FormRet)
			LUA_EVENT_RELOADLUAEND = i; i=i+1;		//重新加载脚本完毕()
			LUA_EVENT_ONGUIDECREATE = i; i=i+1;		//新手面板创建事件(GuideId)
			LUA_EVENT_ONEQUIPMENT = i; i=i+1;			//穿戴装备事件(name, guid, id, site)
			LUA_EVENT_HORSEBUTTONCLICK = i; i=i+1;	//玩家骑马事件 flag:0行走 1:骑马(flag)
			LUA_EVENT_WNDLOADLAYOUT = i; i=i+1;      	//窗口成功加载布局文件(string _LayOutFile, INT _pCurWnd)
			LUA_EVENT_ITEMWNDMOVEITEMIN = i; i=i+1;	//从背包源物品格移动道具到目标窗口(INT _CurItemWindowType, DWORD _SrcItemGUIDataHandle)
			LUA_EVENT_OPENNPCTALK = i; i=i+1;			//打开NPC面板(string _NpcName, UINT64 _NpcGUID, string _Text)
			LUA_EVENT_CLICKNPCTALKITEM = i; i=i+1;	//点击NPC面板上的条目(string _NpcName, string _ItemInfo)
			LUA_EVENT_CLICKTASKMAPLINK = i; i=i+1;	//点击任务追踪面板上的跳地图链接(string _MapKeyName)
			LUA_EVENT_CLICKTASKNPCLINK = i; i=i+1;	//点击任务追踪面板上的NPC链接(string _NpcKeyName)
			LUA_EVENT_DEFENDICONINIT = i; i=i+1;		//二级密码防护控件初始化事件()
			LUA_EVENT_UILINK = i; i=i+1;				//UILink点击事件,用于点击链接触发打开窗口,提交表单,等
			LUA_EVENT_ONITEMUPDATE = i; i=i+1;		//物品更新事件(string _ItemGUID)
			LUA_EVENT_ONITEMATTRCHANGE = i; i=i+1;	//物品属性改变事件(string _ItemGUID)
			LUA_EVENT_ONITEMDESTROY = i; i=i+1;		//物品删除事件(string _ItemGUID)
			LUA_EVENT_ONUISTYLECHANGE = i; i=i+1;		//界面布局发生变化(bool _UseNewStyle)
			LUA_EVENT_ONHEROCREATE = i; i=i+1;		//英雄创建事件(string _DummyGUID)
			LUA_EVENT_ONHERODESTROY = i; i=i+1;		//英雄销毁事件(string _DummyGUID)
			LUA_EVENT_ONMOUSEITEMCLEAR = i; i=i+1;	//鼠标上物品清空事件(DWORD _ItemGUIData)
			LUA_EVENT_OFFEQUIPMENT = i; i=i+1;		//脱装备事件(string GUID)
			LUA_EVENT_AUTOATTACSTOP = i; i=i+1;		//跳地图后挂机停止
			LUA_EVENT_PLAYERADDBUFF = i; i=i+1;		//玩家添加buff(INT _BuffID)
			LUA_EVENT_PLAYERDESTORYBUFF = i; i=i+1;	//玩家销毁buff(INT _BuffID)
			LUA_EVENT_HEROADDBUFF = i; i=i+1;			//英雄添加buff(INT _BuffID)
			LUA_EVENT_HERODESTORYBUFF = i; i=i+1;		//英雄销毁buff(INT _BuffID)
			LUA_EVENT_HERO_CHANGESTATE = i; i=i+1;	//英雄状态改变
			LUA_EVENT_ONHEROADDITEM = i; i=i+1;		//添加物品(string _ItemName,UINT64 _ItemGUID,INT _ItemID)
			LUA_EVENT_PLAYERATTREXTREF = i; i=i+1;	//(string _Info, INT _Type, INT _ChangeType)
			LUA_EVENT_HEROATTREXTREF = i; i=i+1;		//(string _Info, INT _Type, INT _ChangeType)
			LUA_EVENT_PLAYERERRORCODE = i; i=i+1;		//(int ErrorCode)
			LUA_EVENT_HEROERRORCODE = i; i=i+1;		//(int ErrorCode)
			LUA_EVENT_SHIELDREMOVE = i; i=i+1;		//(int ErrorCode)
			LUA_EVENT_INATHLETICSREGION = i; i=i+1;	//(int ErrorCode)
			LUA_EVENT_OUTATHLETICSREGION = i; i=i+1;	//(int ErrorCode)
			LUA_EVENT_INITMAININTERFACE = i; i=i+1;	//()
			LUA_EVENT_SWITICHSKILLACTIVE = i; i=i+1;	//(int skilltype, int active)
			LUA_EVENT_STALLSELL = i; i=i+1;			//(string BuyerName, int ItemCount, string ItemName)
			LUA_EVENT_ITEMCTRLIN = i; i=i+1;			//(INT _Handle, int ItemID, string ItemGUID)
			LUA_EVENT_ITEMCTRLOUT = i; i=i+1;			//(INT _Handle, int ItemID, string ItemGUID)
			LUA_EVENT_CUSTOMDATALOAD = i; i=i+1;		//()
			LUA_EVENT_OPENHEROGUI = i; i=i+1;			//()
			LUA_EVENT_OPENHEROPACKAGE = i; i=i+1;		//()
			LUA_EVENT_OPENDESKWINODW = i; i=i+1;		//()
			LUA_EVENT_CHATCHANNELCHANGE = i; i=i+1;	//聊天类型改变
			LUA_EVENT_UPDATAMALLITEM = i; i=i+1;	
			LUA_EVENT_PROPERTYDATA64 = i; i=i+1;		//角色64位属性改变(UINT64 _RoleID, INT _Type, INT _Data)
			LUA_EVENT_CHOOSEPLAYER = i; i=i+1;			//选中玩家
			LUA_EVENT_HIDECHOOSEPLAYER = i; i=i+1;		//取消玩家
			LUA_EVENT_PACKAGECOUNT = i; i=i+1;			//背包內道具數量
			LUA_EVENT_SKILLPROFICIENCY = i; i=i+1;		//技能熟练度更新
			LUA_EVENT_P2PINVITE = i; i=i+1;				//交易邀请
			LUA_EVENT_P2PLOCK = i; i=i+1;				//交易锁定
			LUA_EVENT_STALLSETPRICE = i; i=i+1;			//摆摊准备上架通知
			LUA_EVENT_VISITSTALLLIST = i; i=i+1;		//查看摆摊列表通知
			LUA_EVENT_HIDEVISITSTALL = i; i=i+1;		//关闭别人摆摊界面
			LUA_EVENT_VISITSTALLBUY = i; i=i+1;			//别人摆摊物品被买
			LUA_EVENT_TRANSFERLEADERTEAM = i; i=i+1;	//移交队长
			LUA_EVENT_DISMISSTEAM = i; i=i+1; 			//解散队伍
			LUA_EVENT_OPENTEAM = i; i=i+1; 				//打开组队面板
			LUA_EVENT_CLOSETEAM = i; i=i+1; 			//关闭组队面板
			LUA_EVENT_ONCHANGEFRIEND = i; i=i+1;		//更新好友信息
			LUA_EVENT_ONFINISHACHIVE = i; i=i+1;		//完成了某个成就,id,状态，1：未完成，2：已完成，3：奖励已领取
			LUA_EVENT_ONACHIVELIST = i; i=i+1;			//成就列表
			LUA_EVENT_JOINTEAM = i; i=i+1;				//有玩家申请入队
			LUA_EVENT_CLOSESYSSETGUI = i; i=i+1;		//关闭设置面板()
			LUA_EVENT_MAILLIST = i; i=i+1;				//邮件列表()
			LUA_EVENT_MAILDETAIL = i; i=i+1;			//邮件内容()
			LUA_EVENT_MAILATTACHMENTOK = i; i=i+1;		//邮件领取成功()
			LUA_EVENT_NPCQUEST = i; i=i+1;         		//npc任务id
			LUA_EVENT_FAMILYINVITE = i; i=i+1;			//邀请玩家加入行会
			LUA_EVENT_FAMILYINVITENOTICE = i; i=i+1;	//受邀加入行会通知
			LUA_EVENT_QUICKCHANGE = i; i=i+1;			//快捷键变更
			LUA_EVENT_STARTSTALL = i; i=i+1;			//开始摆摊是否成功
			LUA_EVENT_OTHERROLEDATA = i; i=i+1;			//其他玩家数据
			LUA_EVENT_OPENTRADEGUI = i; i=i+1;			//打开交易面板()
			LUA_EVENT_OPENSTALLGUI = i; i=i+1;			//打开摆摊面板()
			LUA_EVENT_CLOSEGAMEMALLGUI = i; i=i+1;		//关闭商城面板()
			LUA_EVENT_CLOSEWAREHOUSEGUI = i; i=i+1;		//关闭仓库面板()
			LUA_EVENT_CLOSEADVWAREHOUSEGUI = i; i=i+1; 	//关闭高级仓库面板()
			LUA_EVENT_CLOSETRADEGUI = i; i=i+1;			//关闭交易面板()
			LUA_EVENT_CLOSESTALLGUI = i; i=i+1;			//关闭摆摊面板()
			LUA_EVENT_CAMPAIGNLIST = i; i=i+1;			//活动列表
			LUA_EVENT_FAMILYNOTICECONFIRM = i; i=i+1; 	//修改行会消息确认
			LUA_EVENT_ONLEAVETEAMEX = i; i=i+1;			//离开队伍EX,补充原leave事件不足
			LUA_EVENT_ONJOINTEAMEX = i; i=i+1;			//加入队伍EX,补充原join事件不足
			LUA_EVENT_SKIllAPPLY = i; i=i+1;					//能已使用， 如打出烈火， para[0] = LINKAGEID
			LUA_EVENT_CALLBACKCOUNTCHANGE = i; i=i+1;					//右键交易组队消息个数改变 key,count
			LUA_EVENT_SETTINGPROPCHANGE =  i; i=i+1;		// 某个设置属性的变化 如1018页游走跑模式的切换 para[0] = id, para[1] = value
			LUA_EVENT_OBJDISPEAR =  i; i=i+1;
			LUA_EVENT_PROPERTYDATALIST =  i; i=i+1;
			LUA_EVENT_AUTOMOVEEND = i; i=i+1;			//自动寻路结束
			LUA_EVENT_OTHERPLAYERINFO = i; i=i+1;		//其他玩家信息
			LUA_EVENT_INNERFORCELEVELUP = i; i = i + 1;		//内功升级回调
			LUA_EVENT_COUNT = i; i=i+1;					//事件个数 
			EVENT_DEFAULT_TAG = "0"

			addApi("LUA_EVENT_NONE",LUA_EVENT_NONE);
			addApi("LUA_EVENT_ONPLAYLEVELUP",LUA_EVENT_ONPLAYLEVELUP);
			addApi("LUA_EVENT_ONLOGIN",LUA_EVENT_ONLOGIN);
			addApi("LUA_EVENT_INITRESCOMPLETE",LUA_EVENT_INITRESCOMPLETE);
			addApi("LUA_EVENT_ONENTERMAP",LUA_EVENT_ONENTERMAP);
			addApi("LUA_EVENT_ONADDSKILL",LUA_EVENT_ONADDSKILL);
			addApi("LUA_EVENT_ONADDITEM",LUA_EVENT_ONADDITEM);
			addApi("LUA_EVENT_ONDROPITEM",LUA_EVENT_ONDROPITEM);
			addApi("LUA_EVENT_CHANGEATTACMODE",LUA_EVENT_CHANGEATTACMODE);
			addApi("LUA_EVENT_GETNEWQUEST",LUA_EVENT_GETNEWQUEST);
			addApi("LUA_EVENT_FINISHQUEST",LUA_EVENT_FINISHQUEST);
			addApi("LUA_EVENT_READYQUEST",LUA_EVENT_READYQUEST);
			addApi("LUA_EVENT_DROPQUEST",LUA_EVENT_DROPQUEST);
			addApi("LUA_EVENT_ONADDBUFF",LUA_EVENT_ONADDBUFF);
			addApi("LUA_EVENT_ONPLAYERAPPEAR",LUA_EVENT_ONPLAYERAPPEAR);
			addApi("LUA_EVENT_ONFINISHMASTER",LUA_EVENT_ONFINISHMASTER);
			addApi("LUA_EVENT_ONFINISHMARRY",LUA_EVENT_ONFINISHMARRY);
			addApi("LUA_EVENT_ONJOINFAMILY",LUA_EVENT_ONJOINFAMILY);
			addApi("LUA_EVENT_ONLEAVEFAMILY",LUA_EVENT_ONLEAVEFAMILY);
			addApi("LUA_EVENT_ONACHIEVECASTLE",LUA_EVENT_ONACHIEVECASTLE);
			addApi("LUA_EVENT_ONLOSECASTLE",LUA_EVENT_ONLOSECASTLE);
			addApi("LUA_EVENT_ONNEWMAIL",LUA_EVENT_ONNEWMAIL);
			addApi("LUA_EVENT_ONADDFRIEND",LUA_EVENT_ONADDFRIEND);
			addApi("LUA_EVENT_ONDELFRIEND",LUA_EVENT_ONDELFRIEND);
			addApi("LUA_EVENT_ONJOINTEAM",LUA_EVENT_ONJOINTEAM);
			addApi("LUA_EVENT_ONLEAVETEAM",LUA_EVENT_ONLEAVETEAM);
			addApi("LUA_EVENT_ONP2PTRADEOK",LUA_EVENT_ONP2PTRADEOK);
			addApi("LUA_EVENT_OPENPAKAGEGUI",LUA_EVENT_OPENPAKAGEGUI);
			addApi("LUA_EVENT_OPENSKILLGUI",LUA_EVENT_OPENSKILLGUI);
			addApi("LUA_EVENT_OPENROLEGUI",LUA_EVENT_OPENROLEGUI);
			addApi("LUA_EVENT_OPENMAILGUI",LUA_EVENT_OPENMAILGUI);
			addApi("LUA_EVENT_OPENQUESTGUI",LUA_EVENT_OPENQUESTGUI);
			addApi("LUA_EVENT_OPENSYSSETGUI",LUA_EVENT_OPENSYSSETGUI);
			addApi("LUA_EVENT_OPENFAMILYGUI",LUA_EVENT_OPENFAMILYGUI);
			addApi("LUA_EVENT_OPENVIPGUI",LUA_EVENT_OPENVIPGUI);
			addApi("LUA_EVENT_OPENRANKGUI",LUA_EVENT_OPENRANKGUI);
			addApi("LUA_EVENT_OPENFRIENDGUI",LUA_EVENT_OPENFRIENDGUI);
			addApi("LUA_EVENT_OPENBIGMAPGUI",LUA_EVENT_OPENBIGMAPGUI);
			addApi("LUA_EVENT_OPENBIGCAMPAIGNGUI",LUA_EVENT_OPENBIGCAMPAIGNGUI);
			addApi("LUA_EVENT_OPENWAREHOUSEGUI",LUA_EVENT_OPENWAREHOUSEGUI);
			addApi("LUA_EVENT_OPENADVWAREHOUSEGUI",LUA_EVENT_OPENADVWAREHOUSEGUI);
			addApi("LUA_EVENT_OPENGAMEMALLGUI",LUA_EVENT_OPENGAMEMALLGUI);
			addApi("LUA_EVENT_OPENGAMESETTINGGUI",LUA_EVENT_OPENGAMESETTINGGUI);
			addApi("LUA_EVENT_PROPERTYDATA",LUA_EVENT_PROPERTYDATA);
			addApi("LUA_EVENT_CLOSEQUESTGUI",LUA_EVENT_CLOSEQUESTGUI);
			addApi("LUA_EVENT_CLOSEPACKAGEGUI",LUA_EVENT_CLOSEPACKAGEGUI);
			addApi("LUA_EVENT_CLOSEROLEGUI",LUA_EVENT_CLOSEROLEGUI);
			addApi("LUA_EVENT_CLOSESKILLGUI",LUA_EVENT_CLOSESKILLGUI);
			addApi("LUA_EVENT_ONAPPLYITEM",LUA_EVENT_ONAPPLYITEM);
			addApi("LUA_EVENT_ONTEAMINVITE",LUA_EVENT_ONTEAMINVITE);
			addApi("LUA_EVENT_UPDATASCREENSIZE",LUA_EVENT_UPDATASCREENSIZE);
			addApi("LUA_EVENT_ONQUITEGAME",LUA_EVENT_ONQUITEGAME);
			addApi("LUA_EVENT_ONSHOWFORM",LUA_EVENT_ONSHOWFORM);
			addApi("LUA_EVENT_SUBMITFORMACK",LUA_EVENT_SUBMITFORMACK);
			addApi("LUA_EVENT_RELOADLUAEND",LUA_EVENT_RELOADLUAEND);
			addApi("LUA_EVENT_ONGUIDECREATE",LUA_EVENT_ONGUIDECREATE);
			addApi("LUA_EVENT_ONEQUIPMENT",LUA_EVENT_ONEQUIPMENT);
			addApi("LUA_EVENT_HORSEBUTTONCLICK",LUA_EVENT_HORSEBUTTONCLICK);
			addApi("LUA_EVENT_WNDLOADLAYOUT",LUA_EVENT_WNDLOADLAYOUT);
			addApi("LUA_EVENT_ITEMWNDMOVEITEMIN",LUA_EVENT_ITEMWNDMOVEITEMIN);
			addApi("LUA_EVENT_OPENNPCTALK",LUA_EVENT_OPENNPCTALK);
			addApi("LUA_EVENT_CLICKNPCTALKITEM",LUA_EVENT_CLICKNPCTALKITEM);
			addApi("LUA_EVENT_CLICKTASKMAPLINK",LUA_EVENT_CLICKTASKMAPLINK);
			addApi("LUA_EVENT_CLICKTASKNPCLINK",LUA_EVENT_CLICKTASKNPCLINK);
			addApi("LUA_EVENT_DEFENDICONINIT",LUA_EVENT_DEFENDICONINIT);
			addApi("LUA_EVENT_UILINK",LUA_EVENT_UILINK);
			addApi("LUA_EVENT_ONITEMUPDATE",LUA_EVENT_ONITEMUPDATE);
			addApi("LUA_EVENT_ONITEMATTRCHANGE",LUA_EVENT_ONITEMATTRCHANGE);
			addApi("LUA_EVENT_ONITEMDESTROY",LUA_EVENT_ONITEMDESTROY);
			addApi("LUA_EVENT_ONUISTYLECHANGE",LUA_EVENT_ONUISTYLECHANGE);
			addApi("LUA_EVENT_ONHEROCREATE",LUA_EVENT_ONHEROCREATE);
			addApi("LUA_EVENT_ONHERODESTROY",LUA_EVENT_ONHERODESTROY);
			addApi("LUA_EVENT_ONMOUSEITEMCLEAR",LUA_EVENT_ONMOUSEITEMCLEAR);
			addApi("LUA_EVENT_OFFEQUIPMENT",LUA_EVENT_OFFEQUIPMENT);
			addApi("LUA_EVENT_AUTOATTACSTOP",LUA_EVENT_AUTOATTACSTOP);
			addApi("LUA_EVENT_PLAYERADDBUFF",LUA_EVENT_PLAYERADDBUFF);
			addApi("LUA_EVENT_PLAYERDESTORYBUFF",LUA_EVENT_PLAYERDESTORYBUFF);
			addApi("LUA_EVENT_HEROADDBUFF",LUA_EVENT_HEROADDBUFF);
			addApi("LUA_EVENT_HERODESTORYBUFF",LUA_EVENT_HERODESTORYBUFF);
			addApi("LUA_EVENT_HERO_CHANGESTATE",LUA_EVENT_HERO_CHANGESTATE);
			addApi("LUA_EVENT_ONHEROADDITEM",LUA_EVENT_ONHEROADDITEM);
			addApi("LUA_EVENT_PLAYERATTREXTREF",LUA_EVENT_PLAYERATTREXTREF);
			addApi("LUA_EVENT_HEROATTREXTREF",LUA_EVENT_HEROATTREXTREF);
			addApi("LUA_EVENT_PLAYERERRORCODE",LUA_EVENT_PLAYERERRORCODE);
			addApi("LUA_EVENT_HEROERRORCODE",LUA_EVENT_HEROERRORCODE);
			addApi("LUA_EVENT_SHIELDREMOVE",LUA_EVENT_SHIELDREMOVE);
			addApi("LUA_EVENT_INATHLETICSREGION",LUA_EVENT_INATHLETICSREGION);
			addApi("LUA_EVENT_OUTATHLETICSREGION",LUA_EVENT_OUTATHLETICSREGION);
			addApi("LUA_EVENT_INITMAININTERFACE",LUA_EVENT_INITMAININTERFACE);
			addApi("LUA_EVENT_SWITICHSKILLACTIVE",LUA_EVENT_SWITICHSKILLACTIVE);
			addApi("LUA_EVENT_STALLSELL",LUA_EVENT_STALLSELL);
			addApi("LUA_EVENT_ITEMCTRLIN",LUA_EVENT_ITEMCTRLIN);
			addApi("LUA_EVENT_ITEMCTRLOUT",LUA_EVENT_ITEMCTRLOUT);
			addApi("LUA_EVENT_CUSTOMDATALOAD",LUA_EVENT_CUSTOMDATALOAD);
			addApi("LUA_EVENT_OPENHEROGUI",LUA_EVENT_OPENHEROGUI);
			addApi("LUA_EVENT_OPENHEROPACKAGE",LUA_EVENT_OPENHEROPACKAGE);
			addApi("LUA_EVENT_OPENDESKWINODW",LUA_EVENT_OPENDESKWINODW);
			addApi("LUA_EVENT_CHATCHANNELCHANGE",LUA_EVENT_CHATCHANNELCHANGE);
			addApi("LUA_EVENT_UPDATAMALLITEM",LUA_EVENT_UPDATAMALLITEM);
			addApi("LUA_EVENT_PROPERTYDATA64",LUA_EVENT_PROPERTYDATA64);
			addApi("LUA_EVENT_CHOOSEPLAYER",LUA_EVENT_CHOOSEPLAYER);
			addApi("LUA_EVENT_HIDECHOOSEPLAYER",LUA_EVENT_HIDECHOOSEPLAYER);
			addApi("LUA_EVENT_PACKAGECOUNT",LUA_EVENT_PACKAGECOUNT);
			addApi("LUA_EVENT_SKILLPROFICIENCY",LUA_EVENT_SKILLPROFICIENCY);
			addApi("LUA_EVENT_P2PINVITE",LUA_EVENT_P2PINVITE);
			addApi("LUA_EVENT_P2PLOCK",LUA_EVENT_P2PLOCK);
			addApi("LUA_EVENT_STALLSETPRICE",LUA_EVENT_STALLSETPRICE);
			addApi("LUA_EVENT_VISITSTALLLIST",LUA_EVENT_VISITSTALLLIST);
			addApi("LUA_EVENT_HIDEVISITSTALL",LUA_EVENT_HIDEVISITSTALL);
			addApi("LUA_EVENT_VISITSTALLBUY",LUA_EVENT_VISITSTALLBUY);
			addApi("LUA_EVENT_TRANSFERLEADERTEAM",LUA_EVENT_TRANSFERLEADERTEAM);
			addApi("LUA_EVENT_DISMISSTEAM",LUA_EVENT_DISMISSTEAM);
			addApi("LUA_EVENT_OPENTEAM",LUA_EVENT_OPENTEAM);
			addApi("LUA_EVENT_CLOSETEAM",LUA_EVENT_CLOSETEAM);
			addApi("LUA_EVENT_ONCHANGEFRIEND",LUA_EVENT_ONCHANGEFRIEND);
			addApi("LUA_EVENT_ONFINISHACHIVE",LUA_EVENT_ONFINISHACHIVE);
			addApi("LUA_EVENT_ONACHIVELIST",LUA_EVENT_ONACHIVELIST);
			addApi("LUA_EVENT_JOINTEAM",LUA_EVENT_JOINTEAM);
			addApi("LUA_EVENT_CLOSESYSSETGUI",LUA_EVENT_CLOSESYSSETGUI);
			addApi("LUA_EVENT_MAILLIST",LUA_EVENT_MAILLIST);
			addApi("LUA_EVENT_MAILDETAIL",LUA_EVENT_MAILDETAIL);
			addApi("LUA_EVENT_MAILATTACHMENTOK",LUA_EVENT_MAILATTACHMENTOK);
			addApi("LUA_EVENT_NPCQUEST",LUA_EVENT_NPCQUEST);
			addApi("LUA_EVENT_FAMILYINVITE",LUA_EVENT_FAMILYINVITE);
			addApi("LUA_EVENT_FAMILYINVITENOTICE",LUA_EVENT_FAMILYINVITENOTICE);
			addApi("LUA_EVENT_QUICKCHANGE",LUA_EVENT_QUICKCHANGE);
			addApi("LUA_EVENT_STARTSTALL",LUA_EVENT_STARTSTALL);
			addApi("LUA_EVENT_OTHERROLEDATA",LUA_EVENT_OTHERROLEDATA);
			addApi("LUA_EVENT_OPENTRADEGUI",LUA_EVENT_OPENTRADEGUI);
			addApi("LUA_EVENT_OPENSTALLGUI",LUA_EVENT_OPENSTALLGUI);
			addApi("LUA_EVENT_CLOSEGAMEMALLGUI",LUA_EVENT_CLOSEGAMEMALLGUI);
			addApi("LUA_EVENT_CLOSEWAREHOUSEGUI",LUA_EVENT_CLOSEWAREHOUSEGUI);
			addApi("LUA_EVENT_CLOSEADVWAREHOUSEGUI",LUA_EVENT_CLOSEADVWAREHOUSEGUI);
			addApi("LUA_EVENT_CLOSETRADEGUI",LUA_EVENT_CLOSETRADEGUI);
			addApi("LUA_EVENT_CLOSESTALLGUI",LUA_EVENT_CLOSESTALLGUI);
			addApi("LUA_EVENT_CAMPAIGNLIST",LUA_EVENT_CAMPAIGNLIST);
			addApi("LUA_EVENT_FAMILYNOTICECONFIRM",LUA_EVENT_FAMILYNOTICECONFIRM);
			addApi("LUA_EVENT_ONLEAVETEAMEX",LUA_EVENT_ONLEAVETEAMEX);
			addApi("LUA_EVENT_ONJOINTEAMEX",LUA_EVENT_ONJOINTEAMEX);
			addApi("LUA_EVENT_SKIllAPPLY",LUA_EVENT_SKIllAPPLY);
			addApi("LUA_EVENT_CALLBACKCOUNTCHANGE",LUA_EVENT_CALLBACKCOUNTCHANGE);
			addApi("LUA_EVENT_SETTINGPROPCHANGE",LUA_EVENT_SETTINGPROPCHANGE);
			addApi("LUA_EVENT_OBJDISPEAR",LUA_EVENT_OBJDISPEAR);
			addApi("LUA_EVENT_PROPERTYDATALIST",LUA_EVENT_PROPERTYDATALIST);
			addApi("LUA_EVENT_AUTOMOVEEND",LUA_EVENT_AUTOMOVEEND);
			addApi("LUA_EVENT_OTHERPLAYERINFO",LUA_EVENT_OTHERPLAYERINFO);
			addApi("LUA_EVENT_COUNT",LUA_EVENT_COUNT);
			addApi("EVENT_DEFAULT_TAG",EVENT_DEFAULT_TAG);
		}
	}
}